sonar.projectKey=demo-sonar
sonar.projectName=demo-sonar

sonar.sources=src/main/kotlin
sonar.tests=src/test/kotlin
sonar.java.binaries=build/classes/kotlin/main
sonar.java.test.binaries=build/classes/kotlin/test

sonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml
